image : microsoft/dotnet:latest
stages:
  - build
before_script:
  - 'dotnet restore'
build:
 stage: build
 script:
  - 'dotnet build /property:Version=dev-$CI_BUILD_ID'
  - 'dotnet nuget push /builds/nuxt-irc/dotnet-irc-testing/IrcClientCore/bin/Debug/*.nupkg -k $NUGET_KEY --source https://nuget.rymate.co.uk/'
 tags:
  - docker
