image : microsoft/dotnet:latest
stages:
  - build
before_script:
  - 'dotnet restore'
build:
 stage: build
 script:
  - 'dotnet build /property:Version=1.0.$CI_BUILD_ID-dev'
  - 'dotnet nuget push /builds/nuxt-irc/dotnet-irc-testing/IrcClientCore/bin/Debug/*.nupkg -k $NUGET_KEY --source https://api.nuget.org/v3/index.json'
 tags:
  - docker
