name: .NET Core CI

on: [push]


jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Print env vars
      run: printenv
    - name: Build with dotnet
      run: dotnet build --configuration Release /property:Version=1.0.$(Build.BuildNumber)
