name: .NET Core CI

on: [push]


jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Generate build number
      id: buildnumber
      uses: einaregilsson/build-number@v2 
      with:
        token: ${{secrets.github_token}}        

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100

    - name: Print env vars
      run: printenv

    - name: Build with dotnet
      run: dotnet build --configuration Release /property:Version=1.0.$BUILD_NUMBER-dev

    - name: Publish the package to GPR
      run: dotnet nuget push ./IrcClientCore/bin/Release/*.nupkg --source "github"